#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FiveElements.Resource", IsApplication=true)]

namespace FiveElements
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lizard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int paper = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int right = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int scissors = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spok = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int stone = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnElem = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnLeft = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int btnRight = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btnStart = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int hash = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int imgView = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int result = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int salt = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtSalt = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Elements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int click = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int click1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int click2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int click3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int click4 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int draw = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int draw1 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int draw2 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int lose = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int lose1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int lose2 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int win = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int win1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int win2 = 2130968589;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
